# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0004_auto_20171122_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('adresse1', models.CharField(max_length=100)),
                ('adresse2', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='intervention',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interventions.Client'),
        ),
    ]
