# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 10:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0005_auto_20171124_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='profile',
            new_name='intervention',
        ),
    ]
