# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0006_auto_20171125_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mon_compte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('adresse1', models.CharField(max_length=100)),
                ('adresse2', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
            ],
        ),
    ]
