# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 18:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0007_mon_compte'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intervention',
            old_name='date',
            new_name='date_facture',
        ),
    ]
