# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0008_auto_20171125_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='date_facture',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
