# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0009_auto_20171125_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='moi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('adresse1', models.CharField(max_length=100)),
                ('adresse2', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('nom_rib', models.CharField(max_length=100)),
                ('domiciliation_rib', models.CharField(max_length=100)),
                ('code_banque_rib', models.CharField(max_length=100)),
                ('numero_compte_rib', models.CharField(max_length=100)),
                ('iban_rib', models.CharField(max_length=100)),
                ('code_bic_rib', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Mon_compte',
        ),
    ]
