# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0010_auto_20171125_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='moi',
            name='code_guichet_rib',
            field=models.CharField(default=1234, max_length=100),
            preserve_default=False,
        ),
    ]
