# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0011_moi_code_guichet_rib'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='nb_jour',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='tarif',
        ),
        migrations.AddField(
            model_name='produit',
            name='date_produit',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='produit',
            name='prix_unitaire',
            field=models.FloatField(default=250.5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produit',
            name='quantite',
            field=models.FloatField(default=2.5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produit',
            name='tva',
            field=models.FloatField(default=20),
            preserve_default=False,
        ),
    ]
