# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 19:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0012_auto_20171125_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='name',
            new_name='nom',
        ),
    ]
