# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0013_auto_20171125_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='moi',
            name='mail',
            field=models.EmailField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moi',
            name='siret',
            field=models.CharField(default=12345678, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moi',
            name='tel',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
