# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0014_auto_20171125_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moi',
            name='adresse2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='moi',
            name='contact',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
