# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-02 10:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0015_auto_20171128_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='tva',
        ),
    ]
